language: node_js
node_js:
- stable
branches:
  only:
  - premaster
before_script:
- git config --global user.email "me@andrepolischuk.com"
- git config --global user.name "Travis Builder"
- git remote rm origin
- git remote add origin https://andrepolischuk:${GH_TOKEN}@github.com/andrepolischuk/andrepolischuk.github.io.git
script: npm run deploy
